include theos/makefiles/common.mk

TOOL_NAME = appid2name
appid2name_FILES = appid2name.m
appid2name_PRIVATE_FRAMEWORKS = AppSupport

TWEAK_NAME = Appid2name
Appid2name_FILES = Tweak.xm
Appid2name_FRAMEWORKS = UIKit
Appid2name_PRIVATE_FRAMEWORKS = AppSupport

include $(THEOS_MAKE_PATH)/tool.mk
include $(THEOS_MAKE_PATH)/tweak.mk
